33 - 全体的なリファクタリング
oic-ogma/plant-watcher-app pull request #36
Opened 2017-10-28 09:54 UTC by Dimda

## 説明
プロジェクトの全体的なリファクタリング。

## Issue
#33

2017-10-28 15:12 UTC, youmjww reviewed
申し訳ないんだけど、`common/Spinner.js`や`common/Confirm.js`を見ていると、`const {}`と`return()`に改行が入っていたり、入っていなかったりしているのがあるから一緒に修正して欲しいです。どっちにするかは任せます。

2017-10-28 15:12 UTC, youmjww commented on src/components/Home.js
> +export default Home;
`export default function`形式にしてこの行を削減することって出来ないかな？

CardSectionのソースが参考になると思う

・その他参考リンク
https://hackernoon.com/import-export-default-require-commandjs-javascript-nodejs-es6-vs-cheatsheet-different-tutorial-example-5a321738b50f

2017-10-28 15:12 UTC, youmjww commented on src/Router.js
> +import { Spinner } from './components/common';
そもそも、これはリファクタリングのチケットなのに、fixするのは適当でないと思う

2017-10-28 15:13 UTC, youmjww requested changes
@Dimda 
以上気になった点です。
確認よろしくお願いします。

2017-10-28 15:18 UTC, Dimda commented on src/Router.js
> +import { Spinner } from './components/common';
別のカードにしようと思ったけど後マージコンフリクトでまた面倒臭い。

2017-10-28 15:21 UTC, Dimda commented on src/components/Home.js
> +export default Home;
`export default const` にする事ができるけど今までのコンポーネント(common以外)がdefaultでexportしている。importの方法が変わってくるから統一した方がいいと思った。

2017-10-28 15:29 UTC, Dimda commented
@youmjww Spinner.js は`return()`文はないけど他のやつを統一させた。

2017-10-28 16:08 UTC, Dimda commented on src/components/Home.js
> +export default Home;
確かに`export default function`でいけると思うけど他のところどこにも `function`使ってないからできるだけアローファンクションにしたい。

2017-10-29 12:29 UTC, youmjww commented on src/components/Home.js
> +export default Home;
なるほど
そういう意図ならおｋ

2017-10-29 12:41 UTC, youmjww approved these changes
レビューOKです。
マージします

2017-10-29 12:41 UTC, merged