52 - ホーム画面のレイアウトを変更
oic-ogma/plant-watcher-app pull request #65
Opened 2017-12-08 03:01 UTC by Tyokopai

## 説明
ナビゲーションバーを変更
ホーム画面を削除

## issue
#52

## 備考
背景、ボタンのスタイルなどは他のissueが担当してるのでここでは変更していない

2017-12-08 04:50 UTC, Dimda requested changes

2017-12-08 04:50 UTC, Dimda commented on src/components/Router.js
> +import { IconWrapper } from './common/IconWrapper';
`common`の中に入っている`index.js`で`IconWrapper`を追加したい。そうしたらimportする時に`'./common/IconWrapper'`じゃなくて、`./common`だけで複数のコンポーネントをimportできるようになる。

2017-12-08 04:50 UTC, Dimda commented on src/components/Router.js
> +        <Scene
`hideNavBar={true}`を追加したらnavbarが消える

2017-12-08 04:50 UTC, Dimda commented on src/components/Router.js
> +        <Scene
`hideNavBar={true}`を追加したらnavbarが消える

2017-12-08 04:50 UTC, Dimda commented on src/components/Router.js
> +        <Scene
`hideNavBar={true}`を追加したらnavbarが消える

2017-12-08 04:50 UTC, Dimda commented on src/components/Router.js
> +        <Scene
`hideNavBar={true}`を追加したらnavbarが消える

2017-12-08 05:42 UTC, Tyokopai commented on src/components/Router.js
> +        <Scene
navBarがいらないのは検索ページだけだから、ここだけ適用する

2017-12-09 05:44 UTC, Dimda approved these changes
大丈夫と思う。 👍 
注意するのは一番目のコミットの書き方は違うとできれば`pull`でマージをするより`rebase`でやって欲しい。そっちの方で履歴が綺麗になると思う。
タブバー導入で挙動がおかしいところあるけどそれのために別のタスクカードを用意する。

2017-12-09 05:44 UTC, merged