検索機能をログインしなかったアイテムにも追加する
oic-ogma/plant-watcher-app pull request #66
Opened 2017-12-08 09:00 UTC by 70mas

## 説明
ナビゲーションバーの追加
背景画像の追加
ログインしてない状態でレビューしてください
タイトルの追加

## Issue
#51

2017-12-09 07:57 UTC, Dimda commented
@youmjww @70mas コンフリクト修正をお願い。

2017-12-09 14:22 UTC, youmjww commented
@Dimda コンフリクトの修正しました。
（masterをマージした影響でコミットが見づらくなって申し訳ないですが）レビューよろしくお願いします。

2017-12-13 19:01 UTC, Tyokopai commented on src/components/Router.js
> +          activeTintColor='green'
activeTintColorはボタンと同じ色で #2C9D46 を使う

2017-12-13 19:01 UTC, Tyokopai commented on src/components/Router.js
> +          activeTintColor='green'
authのページのアイコンもgreenになってるから #2C9D46 に修正しておいてほしい

2017-12-15 02:37 UTC, Tyokopai commented
問題なし

2017-12-15 02:38 UTC, racode246 requested changes
問題なし

2017-12-15 02:39 UTC, racode246 approved these changes

2017-12-15 02:39 UTC, merged