54 - 記事一覧のレイアウトを変更
oic-ogma/plant-watcher-app pull request #83
Opened 2018-01-03 18:01 UTC by Dimda

## 説明
- react-native-elementsのカードを適用
- 画像の表示

## Issue
#54

2018-01-04 04:40 UTC, racode246 requested changes

2018-01-04 04:40 UTC, Tyokopai commented on src/components/common/ListItem.js
> +    <Text style={{ paddingBottom: 8 }}>
marginBottom: 20がいいと思う

2018-01-06 09:09 UTC, Dimda commented
@Tyokopai 直した

2018-01-06 13:17 UTC, racode246 approved these changes

2018-01-06 13:18 UTC, merged