62 - 記事詳細画面の追加
oic-ogma/plant-watcher-app pull request #84
Opened 2018-01-06 00:07 UTC by Tyokopai

## 説明
記事詳細ページの作成
テストの作成

## issue
#62 

## 備考
コンフリクトの修正が大変だったので、ブランチを作り直した
ブランチ名は変わってないので、確認のときはローカルのブランチを削除して、リモートのブランチを再度fetchしてください。

2018-01-06 08:45 UTC, Dimda requested changes
動作には時に問題はないと思う、見た目も完璧。👍 
コードの中身はもうちょっと綺麗にする為のコメントを書いておいた。

2018-01-06 08:45 UTC, Dimda commented on src/components/ArticleDetails.js
> +  computeDuration(ms) {
Durationは期間の意味だから、convertTimestampの方がいいと思う。
後timestampはmsではなくsになっている。まあ引数を`timestamp`という名前でもいいけど。

2018-01-06 08:45 UTC, Dimda commented on src/components/ArticleDetails.js
> +              <Text style={uploadDay}>{this.computeDuration(createdAt)}</Text>
上と同じ

2018-01-06 08:45 UTC, Dimda commented on src/containers/ArticleDetailsContainer.js
> +  const {
```
  const { article, articleDecision } = articleDetails;
  const {
    plantName,
    articleContents,
    createdAt,
    currentRating,
  } = article;
```
の方が綺麗になる。

2018-01-06 08:45 UTC, Dimda commented on src/actions/ArticleActions.js
> +export const fetchArticleDecision = () => {
記事を書いた人かどうかのチェックよね？今だと記事決定取得の意味になっているから`checkOwnership`の方が分かりやすいと思う。
これ以外いろんなところで使われてるからそこも編集をお願い。

2018-01-06 08:45 UTC, Dimda commented on src/components/ArticleDetails.js
> +        const style = {
このスタイルは結構長くなっているから`syles`の中の`edit`もしくは`editButton`として追加するがいいと思う。

2018-01-06 08:45 UTC, Dimda commented on src/reducers/ArticleDetailsReducer.js
> +  articleDecision: false
編集できるかどうかのステートなら`editable`がいいと思う。

2018-01-06 08:45 UTC, Dimda commented on src/reducers/ArticleDetailsReducer.js
> +    case DECIDE_USER_ARTICLE:
ここはpayloadを渡さずに二つのアクションに変えたらもっと分かりやすくなると思う。
checkOwnership (アクションクリエーター) -> CAN_EDIT (アクション) -> editable: true (ステート)
checkOwnership (アクションクリエーター) -> CANNOT_EDIT (アクション) -> editable: false (ステート)

2018-01-06 08:45 UTC, Dimda commented on src/actions/ArticleActions.js
> +          type: DECIDE_USER_ARTICLE,
`CAN_EDIT`, payloadなし
  一番下のコメントで理由書いてある。

2018-01-06 08:45 UTC, Dimda commented on src/actions/ArticleActions.js
> +          type: DECIDE_USER_ARTICLE,
`CANNOT_EDIT`, payloadなし
一番下のコメントで理由書いてある。

2018-01-06 09:19 UTC, Dimda commented on src/actions/ArticleActions.js
> +      if (uid === snapshot.val().uid) {
(uid === snapshot.val().uid) ? dispatch({ type: CAN_EDIT }) : dispatch({ type: CANNOT_EDIT })
にしたらもっと短くなる

2018-01-06 10:39 UTC, youmjww reviewed
とりあえず気になったところです

2018-01-06 10:39 UTC, youmjww commented on src/actions/ArticleActions.js
> +  const ref = firebase.database().ref('articles/-KytE808ZYT-X8YPjwGv');
記事IDが決め打ちになってるから別の記事の内容を表示しようとしても出来ない気がする。

2018-01-06 10:39 UTC, youmjww commented on src/actions/ArticleActions.js
> +  const ref = firebase.database().ref('articles/-KytE808ZYT-X8YPjwGv');
ここも決め打ちになってる気がする

2018-01-06 10:39 UTC, youmjww commented on src/components/ArticleDetails.js
> +});
末尾改行が欲しいです。

2018-01-06 10:39 UTC, youmjww commented on src/components/ArticleDetails.js
> +
ここの改行は要らないと思う

2018-01-06 10:41 UTC, Dimda commented on src/actions/ArticleActions.js
> +  const ref = firebase.database().ref('articles/-KytE808ZYT-X8YPjwGv');
記事一覧->記事詳細ページの移動は別のカードでやる。

2018-01-06 10:45 UTC, youmjww commented on src/actions/ArticleActions.js
> +  const ref = firebase.database().ref('articles/-KytE808ZYT-X8YPjwGv');
それなら、記事IDを親コンポーネントから取得してここに当てはめる構造にこのカードの段階でやっておいた方がいいと思う。

2018-01-06 10:47 UTC, Dimda commented on src/actions/ArticleActions.js
> +  const ref = firebase.database().ref('articles/-KytE808ZYT-X8YPjwGv');
今気づいたのは同じコンポーネントを起動する時にdb接続は二回行われてる。それでパフォーマンスに影響がある。多分一つのアクションクリエーターにまとめたほうがいい。

2018-01-06 12:52 UTC, youmjww submitted a review, later dismissed
全体的に見れたから再度レビューです。
今回作成したファイル名とクラス名の文法ですが、他のファイルと合わせて検索しやすくするために`ArticleDetails`より`DetailArticles`の方が(英語的にはおかしい気もするけど)いいと思う。

2018-01-06 12:52 UTC, youmjww commented on src/actions/ArticleActions.js
> +
他のところに合わせるために `// ArticleDetails`というコメントがあったほうがいいと思う

2018-01-06 12:52 UTC, youmjww commented on src/actions/ArticleActions.js
> +  const ref = firebase.database().ref('articles/-KytE808ZYT-X8YPjwGv');
よく考えると、記事一覧->記事詳細前提の機能だからこのアクションは不要な気がする。（DBからわざわざ新たにデータを持ってこなくても既にある）

2018-01-06 12:52 UTC, youmjww commented on __tests__/components/ArticleDetails.test.js
> +});
最終行に改行が欲しいです

2018-01-06 12:52 UTC, youmjww commented on __tests__/reducers/ArticleDetailsReducer.test.js
> +});
最終行に改行が欲しいです

2018-01-06 12:56 UTC, Dimda commented on src/actions/ArticleActions.js
> +  const ref = firebase.database().ref('articles/-KytE808ZYT-X8YPjwGv');
そうね、まあ次のタスクで連携する時にいらないだとしたら、消したらいい。このタスクはUI作るのは一番重要。

2018-01-06 12:57 UTC, Dimda commented
@youmjww DetailArticles はおかしい

2018-01-06 13:04 UTC, youmjww commented
@Dimda

2018-01-06 13:05 UTC, Tyokopai commented on src/components/ArticleDetails.js
> +});
そこは問題では無いと思う

2018-01-06 13:05 UTC, Tyokopai commented on __tests__/components/ArticleDetails.test.js
> +});
そこは問題では無いと思う

2018-01-06 13:06 UTC, youmjww commented
間違えて送信してしまった・・・
この場合は他に合わせるより文法？を優先すべき？

2018-01-06 13:11 UTC, Tyokopai commented on src/components/ArticleDetails.js
> +        const style = {
最初そうしてたけど、circle ciとエディタ上でエラーでてるからこの記述にしてる

2018-01-06 13:49 UTC, Dimda commented on src/components/ArticleDetails.js
> +        const style = {
ファンクションが`render`の中に入ってたからおかしかったかな。
```
  editOrBookmark(editable) {
    if (editable === true) {
      return (
        <Text style={styles.edit}>編集</Text>
      );
    } else {
      return (
        <Icon type='font-awesome' name='bookmark-o' color='#D04255' size={30}/>
      );
    }
  }
```
と
`{this.editOrBookmark(editable)}`
に変えたらエラー出てない。

2018-01-06 13:57 UTC, Dimda commented
@Tyokopai `editOrBookmark`のところだけ直してくれたらもうマージする。それ以外問題ないと思う。

2018-01-06 21:28 UTC, Tyokopai commented
修正しておいた

2018-01-07 03:34 UTC, Dimda approved these changes

2018-01-07 03:34 UTC, merged